WorldName: #You must generate the world yourself, everything that will not be in the radius of the schematics of the map will not be cleared, I advise you to put the schematics from -64 to 320 height and also put the barer exactly on the radius of the schematics
  VoidWorld
MapName:
  RR-NewMap
MapCenter: #default y = 64
  0.5, 0.5
SpawnCoordinates: #U can write more spawnpoint
  - '0.5, 65, -16.5' #1
  - '-11.5, 65, -11.5' #2
  - '-16.5, 65, 0.5' #3
  - '-11.5, 65, 12.5' #4
  - '0.5, 65, 17.5' #5
  - '12.5, 65, 12.5' #6
  - '17.5, 65, 0.5' #7
  - '12.5, 65, -11.5' #8
WorldBorderRadius:
  50
TimeToShrink: #INSECOND!!!!
  480
PlayerNeedToStart:
  8
Structures:
  - 'RR-BigCastle'
  - 'RR-BrokenTexture'
  - 'RR-Caves'
  - 'RR-RandomTexture'
  - 'RR-Ruins'
  - 'RR-SmallCastle'
  - 'RR-Well'
mysql: #todo Надо сделать поддежку баз SQLite
  host: your-mysql-host
  port: 3306
  database: your-mysql-database
  username: your-mysql-username
  password: your-mysql-password
BlackList:
  - 'JIGSAW'